### ISSUE TITLE
Command Path missing slash on github version

### ISSUE THREAD

**Issue by OzBob** [jeffwmartinez/appservicedotnetframework.github.io#3]
https://github.com/jeffwmartinez/appservicedotnetframework.github.io/blob/master/README.md
says:
"Framework.NETFramework"
but
Raw 
https://raw.githubusercontent.com/jeffwmartinez/appservicedotnetframework.github.io/master/README.md
says correct version:
"Framework\\.NETFramework"

Screenshots shows that it has cached a copy that says the wrong thing:

![image](https://user-images.githubusercontent.com/1796771/85676329-15f96800-b6f9-11ea-8e0f-b286418b39e8.png)

**Comment by jeffwmartinez** [comment]
Content was moved to our blog and this fix is located there.  Thank you!!
[https://azure.github.io/AppService/2020/06/09/NET-Framework-4.8-is-coming-to-App-Service.html](url)
